spring.application.name=Zp Tank

spring.datasource.url=jdbc:postgresql://localhost:5432/zptank
spring.datasource.username=postgres
spring.datasource.password=lahata
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true

