CREATE TABLE addresses (
                           id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                           city VARCHAR(255),
                           postal_code VARCHAR(50),
                           street VARCHAR(255),
                           house_number VARCHAR(50)
);

CREATE TABLE products (
                          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                          name VARCHAR(255)
);

CREATE TABLE intermediaries (
                                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                name VARCHAR(255),
                                discount_price NUMERIC(19, 2)
);

CREATE TABLE waybills (
                          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                          waybill_number VARCHAR(255),
                          issue_date DATE
);

CREATE TABLE tractors (
                          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                          registration_number VARCHAR(100),
                          brand VARCHAR(255),
                          model VARCHAR(255),
                          periodic_inspection_date DATE,
                          insurance_valid_until DATE,
                          red_stripe_valid_until DATE,
                          tachograph_reading_date DATE,
                          tachograph_calibration_date DATE,
                          gps VARCHAR(255)
);

CREATE TABLE trailers (
                          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                          registration_number VARCHAR(100),
                          capacity NUMERIC(19, 3),
                          insurance_valid_until DATE,
                          periodic_inspection_date DATE,
                          intermediate_inspection_date DATE,
                          red_stripe_valid_until DATE,
                          on_legalization_valid_until DATE,
                          pb_legalization_valid_until DATE
);

CREATE TABLE tanker_trucks (
                               id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                               registration_number VARCHAR(100),
                               brand VARCHAR(255),
                               model VARCHAR(255),
                               capacity NUMERIC(19, 3),
                               insurance_valid_until DATE,
                               periodic_inspection_date DATE,
                               intermediate_inspection_date DATE,
                               red_stripe_valid_until DATE,
                               on_legalization_valid_until DATE,
                               pb_legalization_valid_until DATE,
                               tachograph_reading_date DATE,
                               tachograph_calibration_date DATE,
                               gps VARCHAR(255)
);

CREATE TABLE transport_sets (
                                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                tractor_id BIGINT UNIQUE,
                                trailer_id BIGINT UNIQUE,
                                tanker_truck_id BIGINT UNIQUE,
                                active BOOLEAN NOT NULL,
                                CONSTRAINT fk_transport_set_tractor
                                    FOREIGN KEY (tractor_id) REFERENCES tractors(id),
                                CONSTRAINT fk_transport_set_trailer
                                    FOREIGN KEY (trailer_id) REFERENCES trailers(id),
                                CONSTRAINT fk_transport_set_tanker_truck
                                    FOREIGN KEY (tanker_truck_id) REFERENCES tanker_trucks(id),
                                CONSTRAINT chk_transport_set_configuration
                                    CHECK (
                                        (
                                            tanker_truck_id IS NOT NULL
                                                AND tractor_id IS NULL
                                                AND trailer_id IS NULL
                                            )
                                            OR
                                        (
                                            tanker_truck_id IS NULL
                                                AND tractor_id IS NOT NULL
                                                AND trailer_id IS NOT NULL
                                            )
                                        )
);

CREATE TABLE clients (
                         id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                         tax_id VARCHAR(100),
                         name VARCHAR(255),
                         company_address_id BIGINT UNIQUE,
                         phone VARCHAR(100),
                         email VARCHAR(255),
                         notes TEXT,
                         login VARCHAR(255),
                         password VARCHAR(255),
                         CONSTRAINT fk_client_company_address
                             FOREIGN KEY (company_address_id) REFERENCES addresses(id)
);

CREATE TABLE delivery_addresses (
                                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                    city VARCHAR(255),
                                    postal_code VARCHAR(50),
                                    street VARCHAR(255),
                                    house_number VARCHAR(50),
                                    client_id BIGINT NOT NULL,
                                    CONSTRAINT fk_delivery_address_client
                                        FOREIGN KEY (client_id) REFERENCES clients(id)
);

CREATE TABLE employees (
                           id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                           first_name VARCHAR(255),
                           last_name VARCHAR(255),
                           phone VARCHAR(100),
                           email VARCHAR(255),
                           role VARCHAR(20) NOT NULL,
                           login VARCHAR(255),
                           password VARCHAR(255),
                           workplace_instruction BOOLEAN NOT NULL,
                           kse_certificate BOOLEAN NOT NULL,
                           medical_examination_valid_until DATE,
                           training_valid_until DATE,
                           health_and_safety_valid_until DATE
);

CREATE TABLE drivers (
                         id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                         first_name VARCHAR(255),
                         last_name VARCHAR(255),
                         phone VARCHAR(100),
                         login VARCHAR(255),
                         password VARCHAR(255),
                         active BOOLEAN NOT NULL,
                         transport_set_id BIGINT UNIQUE,
                         driver_card_valid_until DATE,
                         adr_valid_until DATE,
                         identity_document_valid_until DATE,
                         psychological_examination_valid_until DATE,
                         tdt_valid_until DATE,
                         driving_license_valid_until DATE,
                         health_and_safety_training_valid_until DATE,
                         medical_examination_valid_until DATE,
                         CONSTRAINT fk_driver_transport_set
                             FOREIGN KEY (transport_set_id) REFERENCES transport_sets(id)
);

CREATE TABLE loading_terminals (
                                   id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                   address_id BIGINT UNIQUE,
                                   quantity NUMERIC(19, 3),
                                   CONSTRAINT fk_loading_terminal_address
                                       FOREIGN KEY (address_id) REFERENCES addresses(id)
);

CREATE TABLE order_requests (
                                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                status VARCHAR(50) NOT NULL,
                                created_at TIMESTAMP,
                                client_id BIGINT NOT NULL,
                                product_id BIGINT NOT NULL,
                                quantity NUMERIC(19, 3),
                                price NUMERIC(19, 2),
                                execution_date DATE,
                                notes TEXT,
                                order_id BIGINT,
                                CONSTRAINT fk_order_request_client
                                    FOREIGN KEY (client_id) REFERENCES clients(id),
                                CONSTRAINT fk_order_request_product
                                    FOREIGN KEY (product_id) REFERENCES products(id)
);

CREATE TABLE orders (
                        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        status VARCHAR(50) NOT NULL,
                        created_at TIMESTAMP,
                        execution_date DATE,
                        planned_delivery_date DATE,
                        delivery_date DATE,
                        intermediary_id BIGINT UNIQUE,
                        waybill_id BIGINT UNIQUE,
                        delivery_address_id BIGINT NOT NULL,
                        transport_id BIGINT,
                        CONSTRAINT fk_order_intermediary
                            FOREIGN KEY (intermediary_id) REFERENCES intermediaries(id),
                        CONSTRAINT fk_order_waybill
                            FOREIGN KEY (waybill_id) REFERENCES waybills(id),
                        CONSTRAINT fk_order_delivery_address
                            FOREIGN KEY (delivery_address_id) REFERENCES delivery_addresses(id)
);

ALTER TABLE order_requests
    ADD CONSTRAINT fk_order_request_order
        FOREIGN KEY (order_id) REFERENCES orders(id);

CREATE TABLE transports (
                            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                            status VARCHAR(50) NOT NULL,
                            driver_id BIGINT NOT NULL,
                            loading_terminal_id BIGINT NOT NULL,
                            loading_date DATE,
                            unloading_date DATE,
                            CONSTRAINT fk_transport_driver
                                FOREIGN KEY (driver_id) REFERENCES drivers(id),
                            CONSTRAINT fk_transport_loading_terminal
                                FOREIGN KEY (loading_terminal_id) REFERENCES loading_terminals(id)
);

ALTER TABLE orders
    ADD CONSTRAINT fk_order_transport
        FOREIGN KEY (transport_id) REFERENCES transports(id);

CREATE TABLE loading_terminal_products (
                                           loading_terminal_id BIGINT NOT NULL,
                                           product_id BIGINT NOT NULL,
                                           PRIMARY KEY (loading_terminal_id, product_id),
                                           CONSTRAINT fk_ltp_terminal
                                               FOREIGN KEY (loading_terminal_id) REFERENCES loading_terminals(id),
                                           CONSTRAINT fk_ltp_product
                                               FOREIGN KEY (product_id) REFERENCES products(id)
);

CREATE TABLE huzarsent (
                           id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                           order_id BIGINT UNIQUE,
                           sent VARCHAR(255),
                           ks VARCHAR(255),
                           kr VARCHAR(255),
                           kd VARCHAR(255),
                           CONSTRAINT fk_huzarsent_order
                               FOREIGN KEY (order_id) REFERENCES orders(id)
);

CREATE INDEX idx_order_requests_client ON order_requests(client_id);
CREATE INDEX idx_order_requests_product ON order_requests(product_id);
CREATE INDEX idx_order_requests_order ON order_requests(order_id);
CREATE INDEX idx_delivery_addresses_client ON delivery_addresses(client_id);
CREATE INDEX idx_orders_delivery_address ON orders(delivery_address_id);
CREATE INDEX idx_orders_transport ON orders(transport_id);
CREATE INDEX idx_transports_driver ON transports(driver_id);
CREATE INDEX idx_transports_terminal ON transports(loading_terminal_id);
